version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant_data:/qdrant/data
    ports:
      - "6333:6333"
      - "6334:6334"

  fastapi:
    build: .
    depends_on:
      - qdrant
    ports:
      - "8000:8000"

volumes:
  qdrant_data:
